name: github-ci.yml

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build . -t sarcng-api-image

  EC2-Deploy:

    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ASIAVM4F32DWZ6HXAEAI
      AWS_SECRET_ACCESS_KEY: VECOP31VEhTR8/9nEUjEAoB+tQ66MHC4k9vb3NzW 
      AWS_REGION: us-east-1

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}