name: github-ci.yml

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build . -t sarcng-api-image

  EC2-Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIAVM4F32DWZ6HXAEAI
        aws-secret-access-key: VECOP31VEhTR8/9nEUjEAoB+tQ66MHC4k9vb3NzW
        aws-region: us-east-1